version: '3.0'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  web-app:
    image: node:latest
    container_name: web-app
    ports:
      - 80:80
    volumes:
      - /Users/dominique/Documents/masters/bigdata/webapp:/app
    working_dir: /app
    depends_on: 
      - redis
    environment:
      - REDIS_HOST=redis
    command: node server.js
  pub:
    image: node:latest
    container_name: pub
    volumes:
      - /Users/dominique/Documents/masters/bigdata/publisher:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: node server.js