version: '3.0'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  web-app:
    image: node:latest
    container_name: web-app
    ports:
      - 80:80
    volumes:
      - $WEB_APP_PATH:/app
    working_dir: /app
    depends_on: 
      - redis
    environment:
      - REDIS_HOST=redis
    command: node server.js
  # publisher-app: # for testing
  #   image: node:latest
  #   container_name: pub
  #   volumes:
  #     - $PUBLISHER_APP_PATH:/app
  #   working_dir: /app
  #   environment:
  #     - REDIS_HOST=redis
  #   depends_on: 
  #     - redis
  #   command: node server.js