version: '3.0'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  web-app:
    build: .
    container_name: web-app
    ports:
      - 80:80
    depends_on: 
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379